name = "billionaireking/m000-assignment"
version = "0.0.0"
compiler = "v1.1.19"
plutus = "v3"
license = "Apache-2.0"

[repository]
user = "billionaireking"
project = "m000-assignment"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.0.0"
source = "github"

[config]

[config.default]
network_id = 41
